INSERT INTO course VALUES
('CEO-325', 'FINITE ELEMENT METHOD'),
('EEO-325', 'OPTIMIZATION TECHNIQUES'),
('MEO-325', 'MODELING AND SIMULATION'),
('ECO-325(a)', 'MEMS & SENSOR DESIGN'),
('ECO-325(b)', 'TELECOMMUNICATION SYSTEMS'),
('CSO-324', 'COMPUTER GRAPHICS'),
('CHO-326(b)', 'ENGINEERING OPTIMIZATION'),
('HUO-325', 'DYNAMICS OF BEHAVIORAL SCIENCES IN INDUSTRY'),
('CMO-329', 'BIONANOTECHNOLOGY'),
('MAO-325(b)', 'STATISTICAL TESTING & QUALITY CONTROL');